### ISSUE TITLE
BettingGame: more configurable options

### ISSUE THREAD

**Issue by xNifty** [xNifty/niftybot-discord#16]
Allow the server owner to configure the following:

- Time between []helpme uses (default to 24h)
- Threshold for []helpme minimum (i.e. once at 500 credits don't allow it to be used)
  - Possible: if 0, use the setting to start cooldown once out of credits
- Force multiple of x (i.e. force bets to be a multiple of 10 (10, 20, 30...500, etc)
- Only allow []helpme after configured cooldown following loss of all credits or if below betting threshold

**Comment by netwrksolutions** [comment]
On the time between []helpme uses, consider a cooldown blocking users from immediately using []helpme after losing everything even if it's been greater than 24hrs since their last use.

**Comment by xNifty** [comment]
> On the time between []helpme uses, consider a cooldown blocking users from immediately using []helpme after losing everything even if it's been greater than 24hrs since their last use.

I'll add this to the list of settings the server owner can use.

**Comment by xNifty** [comment]
[**@netwrksolutions**](https://github.com/netwrksolutions) commented on [Sep 14, 2017, 6:45 PM EDT](https://github.com/xNifty/niftybot-discord/issues/16#issuecomment-329629216 "2017-09-14T22:45:41Z - Replied by Github Reply Comments"):
> On the time between []helpme uses, consider a cooldown blocking users from immediately using []helpme after losing everything even if it's been greater than 24hrs since their last use.

I'll add this to the list of settings the server owner can use.

**Comment by xNifty** [comment]
I think this cog is good as it stands; if someone would like to implement the missing portions please feel free to do so and submit a pull request.
