### ISSUE TITLE
Feature Request - Discord @everyone supression

### ISSUE THREAD

**Issue by netwrksolutions** [xNifty/niftybot-discord#24]
To ensure that you don't get spammed with @everyone commands in your discord channels it would be great to have moderator features with NiftyBot that would delete user posts that use the '@everyone' call out.  Basically start a moderator module for the bot that can be built on.

**Comment by xNifty** [comment]
Technically added with https://github.com/xNifty/niftybot-discord/commit/a598b675150810fb0fe22d24ca4314afea0d2134, but there is nothing I can do remove the notification that discord shows; I can simply delete the message or extend that functionality further to do something else.

**Comment by xNifty** [comment]
Reopened for following: not closing any issue marked "ready for merge" until merged into master
