### ISSUE TITLE
Betting Game:  Reset Command Request

### ISSUE THREAD

**Issue by netwrksolutions** [xNifty/niftybot-discord#44]
If the programmer could incorporate a reset command for the betting game to clear cache allowing you to run a fresh round weekly, monthly, etc.  This reset would be only for the Betting Game and leave all other cogs untouched.

**Comment by xNifty** [comment]
Should be pretty straight forward to add.

**Comment by xNifty** [comment]
Added with 705fe9725dc677569be830f87ce8f54177a168ad
Finished with 33c24a4c8cd23fa584bac032399e14fb89cacd34
